### ISSUE TITLE
Couple Files finds non-existing files

### ISSUE THREAD

**Issue by gopar** [ag91/code-compass#36] opened 2023-02-24 16:00 UTC
I've noticed that when calling `code-compass-coupling-files`, the result may sometimes spit out file(s) that no longer exists.

There should be some type of validator against the files it is suggesting.

**Comment by ag91** [comment] 2023-02-24 16:10
mmm most likely because it is using the whole git history, where also deleted files are mentioned. 
Good finding, I will look into that

**Comment by ag91** [comment] 2023-03-06 22:25
any chance you could try again with the latest version? 
I just patched to exclude non-existing files but I didn't have a repository at hand that let me reproduce your issue

**Comment by gopar** [comment] 2023-03-06 23:58
Hey, don't have repository handy at the moment (Got let go at job and with that the problem repository).
If I encounter it again I will let you know :)

**Comment by gopar** [comment] 2023-03-07 00:26
With that said, I don't mind helping out as a maintainer on this package. Really love what this is bringing to emacs :)

**Comment by ag91** [comment] 2023-03-08 10:40
okay no problem. Sorry to hear that, how are you doing?
I may take you up for the co-maintainer proposal: let me see if support demand increases with the publishing on melpa. Or did you mean you have plans to extend code compass?

I will close this, but feel free to reopen in case you can reproduce ;)

**Closed by ag91** 2023-03-08 10:40 UTC
